### PR TITLE
feat: better streaming of buffer text

### PR DESCRIPTION
**Pull request by olimorris**
Stumbled upon this on my quest to make the plugin appear more ChatGPT like

### CODE REVIEW

**Comment by stevearc** [comment]
Oh nice, thanks!

**Comment by olimorris** [comment]
That didn't work?!

**Comment by stevearc** [comment]
Seemed to break, didn't have the time to debug. I assume it's something to do with the line iterator not handling the unbuffered results well

**Comment by olimorris** [comment]
Bizarrely, it worked fine for myself for a couple of days. Then I had to wrap the buffer output in `vim.schedule` calls. But streams really nicely

**Pull request merged**
